import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class ReportService {
  static Future<void> generateDashboardReport({
    required String staffName,
    required String totalInvoices,
    required String totalLeads,
    required String totalTasks,
    required String totalProjects,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('CRM Performance Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text(DateFormat('yyyy-MM-dd').format(DateTime.now())),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Staff: $staffName', style: pw.TextStyle(fontSize: 18)),
              pw.SizedBox(height: 30),
              pw.TableHelper.fromTextArray(
                context: context,
                data: <List<String>>[
                  <String>['Category', 'Total Value'],
                  <String>['Invoices', totalInvoices],
                  <String>['Leads', totalLeads],
                  <String>['Tasks', totalTasks],
                  <String>['Projects', totalProjects],
                ],
              ),
              pw.SizedBox(height: 50),
              pw.Footer(
                trailing: pw.Text('Generated by Flutex Admin Pro'),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
